#!/usr/bin/env -S deno run -A
/**
 * @module
 * Build the Claude Code / Codex plugin payload tree from the engine repo.
 *
 * Implements FR-E70 (plugin-first distribution). The plugin lives in a
 * dedicated public repo (`korchasa/flowai-workflow-plugins`) and is
 * autogenerated from this repo on every release tag by
 * `scripts/sync-plugins-repo.ts` (FR-E72). The output of
 * {@link buildPluginPayload} is a directory tree byte-equal to what gets
 * committed into that repo:
 *
 * ```
 * <outDir>/
 *   .claude-plugin/marketplace.json    # version pinned to <opts.version>
 *   plugins/flowai-workflow/
 *     .claude-plugin/plugin.json       # version pinned to <opts.version>
 *     README.md, agents/, skills/      # verbatim copy of claude-plugin/
 *     engine/<engine TS sources>       # cli.ts, engine.ts, init/, ...
 *     engine/deno.json                 # patched: no publish, no version
 *     .flowai-workflow/<name>/         # bundled workflows (no per-run dirt)
 * ```
 *
 * File enumeration uses `git ls-files` from `<engineRoot>` so the payload
 * tracks the repo's source-of-truth file set: gitignored content
 * (`.flowai-workflow/<name>/runs/`, `.flowai-workflow/<name>/memory/agent-*.md`,
 * `.template.json`, build artefacts) is excluded for free.
 *
 * CLI usage:
 *
 *   deno run -A scripts/build-plugin-payload.ts \
 *     --engine-root . --version 0.7.12 --out-dir dist/plugin-payload
 */

import { dirname, join, relative, resolve } from "@std/path";

/** Options accepted by {@link buildPluginPayload}. */
export interface BuildPayloadOptions {
  /** Absolute path to the engine repo root (contains `deno.json`). */
  engineRoot: string;
  /** Version string pinned into both `marketplace.json` and `plugin.json`. */
  version: string;
  /** Absolute path to the output directory. Created/cleared if necessary. */
  outDir: string;
  /**
   * Override the file-enumeration callback. Production code calls
   * {@link gitLsFiles}; tests inject a synthetic file list to avoid
   * depending on a git working tree.
   */
  enumerateFiles?: (engineRoot: string) => Promise<string[]>;
}

/** Diagnostic summary of a build. */
export interface BuildResult {
  /** Absolute output paths created or overwritten. */
  filesWritten: string[];
  /** Manifests that had their `version` field substituted. */
  manifestsUpdated: string[];
}

/**
 * Substitute the `version` field at the top level of a JSON document.
 * Returns the new JSON text (preserving formatting where possible) and
 * a flag indicating whether the field was actually present.
 *
 * Pure — works on text, not parsed objects, to keep manifests
 * round-trippable for human readers and `git diff`-friendly.
 */
export function substituteVersion(
  json: string,
  version: string,
): { text: string; replaced: boolean } {
  // Match `"version": "X.Y.Z"` at any indent; capture the surrounding
  // punctuation so we can keep the existing whitespace/comma.
  const re = /("version"\s*:\s*)"[^"]*"/;
  if (!re.test(json)) return { text: json, replaced: false };
  return { text: json.replace(re, `$1"${version}"`), replaced: true };
}

/**
 * Decide where (if anywhere) an engine-repo file lands inside the
 * plugin payload. Returns the destination path RELATIVE to `<outDir>`,
 * or `null` if the file should be skipped.
 *
 * Pure — drives the test matrix for payload-shape regressions.
 */
export function classifyPayloadFile(relPath: string): string | null {
  // Tests never ship in the payload.
  if (relPath.endsWith("_test.ts")) return null;
  // The plugin source tree is copied verbatim to the payload root.
  if (relPath.startsWith("claude-plugin/")) {
    return relPath.slice("claude-plugin/".length);
  }
  // Bundled workflows live alongside the engine source, preserving the
  // `.flowai-workflow/` prefix so agent-prompt relative paths keep
  // working post-install.
  if (relPath.startsWith(".flowai-workflow/")) {
    // Drop per-run dirt that managed to slip past the gitignore filter.
    if (/\/runs\//.test(relPath)) return null;
    if (/\/memory\/agent-[^/]+\.md$/.test(relPath)) return null;
    if (relPath.endsWith("/.template.json")) return null;
    if (relPath.endsWith(".template.json")) return null;
    return join("plugins/flowai-workflow", relPath);
  }
  // Engine source: root *.ts plus init/*.ts. Tests already filtered above.
  if (relPath.endsWith(".ts")) {
    // Skip scripts/, .claude/, documents/, anything not part of the engine
    // runtime that the plugin doesn't need at runtime.
    if (relPath.startsWith("scripts/")) return null;
    if (relPath.startsWith(".claude/")) return null;
    if (relPath.startsWith("documents/")) return null;
    if (relPath.startsWith("claude-plugin/")) return null; // unreachable, already handled
    return join("plugins/flowai-workflow/engine", relPath);
  }
  // deno.json travels with the engine so JSR import-map resolves
  // inside the plugin install.
  if (relPath === "deno.json") {
    return "plugins/flowai-workflow/engine/deno.json";
  }
  // Everything else (README at repo root, AGENTS.md, CI configs, docs,
  // scripts, etc.) is not part of the runtime payload.
  return null;
}

/**
 * Patch the engine's `deno.json` for shipment inside the plugin payload:
 * strip the `publish` stanza (the plugin install never publishes to JSR
 * from this manifest), drop `tasks` that only make sense in the source
 * repo (compile, release, sync-plugins, check), and remove the `version`
 * field (the plugin's own `plugin.json` is the single source of truth
 * for the user-facing version inside the plugin).
 *
 * Pure — text in, text out.
 */
export function patchEngineDenoJson(json: string): string {
  const obj = JSON.parse(json) as Record<string, unknown>;
  delete obj.publish;
  delete obj.version;
  // Keep imports + lint + fmt + the test task so consumers can run
  // engine tests if they want; drop developer tasks that reference
  // files not in the payload.
  if (obj.tasks && typeof obj.tasks === "object") {
    const keep = new Set(["test", "test:lib", "test:engine"]);
    const tasks = obj.tasks as Record<string, string>;
    for (const key of Object.keys(tasks)) {
      if (!keep.has(key)) delete tasks[key];
    }
  }
  return JSON.stringify(obj, null, 2) + "\n";
}

/**
 * Default file enumerator: shells out to `git ls-files` from
 * `<engineRoot>`. Returns sorted paths relative to that root.
 *
 * Production callers leave `enumerateFiles` unset; this function is
 * still exported so callers that need to inspect the file set without
 * running the full build (CI smoke checks, doctor commands) can reuse
 * the exact same enumeration logic.
 */
export async function gitLsFiles(engineRoot: string): Promise<string[]> {
  const output = await new Deno.Command("git", {
    args: ["-C", engineRoot, "ls-files"],
    stdout: "piped",
    stderr: "piped",
  }).output();
  if (!output.success) {
    throw new Error(
      `git ls-files failed in ${engineRoot}: ${
        new TextDecoder().decode(output.stderr).trim()
      }`,
    );
  }
  const text = new TextDecoder().decode(output.stdout);
  return text.split("\n").filter((s) => s.length > 0).sort();
}

/**
 * Build the plugin payload tree at `opts.outDir`. Overwrites any
 * existing content under `outDir`. Returns a build summary for callers
 * that want to log file counts or assert specific manifests landed.
 */
export async function buildPluginPayload(
  opts: BuildPayloadOptions,
): Promise<BuildResult> {
  const engineRoot = resolve(opts.engineRoot);
  const outDir = resolve(opts.outDir);
  const enumerate = opts.enumerateFiles ?? gitLsFiles;

  // Reset output directory so stale files from prior builds do not leak
  // into the synced payload (idempotency contract of FR-E72).
  await Deno.remove(outDir, { recursive: true }).catch((err) => {
    if (!(err instanceof Deno.errors.NotFound)) throw err;
  });
  await Deno.mkdir(outDir, { recursive: true });

  const files = await enumerate(engineRoot);
  const filesWritten: string[] = [];
  const manifestsUpdated: string[] = [];

  for (const relPath of files) {
    const destRel = classifyPayloadFile(relPath);
    if (destRel === null) continue;
    const srcAbs = join(engineRoot, relPath);
    const dstAbs = join(outDir, destRel);
    await Deno.mkdir(dirname(dstAbs), { recursive: true });

    // Manifest files get the version substituted; the engine's deno.json
    // gets the publish stanza stripped; everything else is a verbatim
    // byte-copy.
    if (
      destRel === ".claude-plugin/marketplace.json" ||
      destRel === "plugins/flowai-workflow/.claude-plugin/plugin.json"
    ) {
      const src = await Deno.readTextFile(srcAbs);
      const { text, replaced } = substituteVersion(src, opts.version);
      if (!replaced) {
        throw new Error(
          `${relPath}: expected a top-level "version" field; manifest is malformed.`,
        );
      }
      await Deno.writeTextFile(dstAbs, text);
      manifestsUpdated.push(dstAbs);
    } else if (destRel === "plugins/flowai-workflow/engine/deno.json") {
      const src = await Deno.readTextFile(srcAbs);
      await Deno.writeTextFile(dstAbs, patchEngineDenoJson(src));
    } else {
      await Deno.copyFile(srcAbs, dstAbs);
    }
    filesWritten.push(dstAbs);
  }

  if (manifestsUpdated.length !== 2) {
    throw new Error(
      `Expected to update 2 manifests (marketplace.json + plugin.json); ` +
        `got ${manifestsUpdated.length}. Source tree is missing one of them.`,
    );
  }

  return { filesWritten, manifestsUpdated };
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

interface CliArgs {
  engineRoot: string;
  version: string;
  outDir: string;
}

/** Parse CLI args for the script's stand-alone mode. Exported for tests. */
export function parseCliArgs(argv: string[]): CliArgs | { help: string } {
  let engineRoot = ".";
  let version = "";
  let outDir = "";
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    switch (arg) {
      case "--engine-root":
        engineRoot = argv[++i] ?? "";
        break;
      case "--version":
        version = argv[++i] ?? "";
        break;
      case "--out-dir":
        outDir = argv[++i] ?? "";
        break;
      case "-h":
      case "--help":
        return {
          help:
            "Usage: build-plugin-payload --engine-root <dir> --version <semver> --out-dir <dir>",
        };
      default:
        throw new Error(`Unknown argument: ${arg}`);
    }
  }
  if (!version) throw new Error("--version is required");
  if (!outDir) throw new Error("--out-dir is required");
  return { engineRoot, version, outDir };
}

if (import.meta.main) {
  const parsed = parseCliArgs(Deno.args);
  if ("help" in parsed) {
    console.log(parsed.help);
    Deno.exit(0);
  }
  const result = await buildPluginPayload(parsed);
  const relativeFiles = result.filesWritten.map((p) =>
    relative(parsed.outDir, p)
  ).sort();
  console.log(
    `Wrote ${relativeFiles.length} files to ${parsed.outDir} ` +
      `(manifests pinned to v${parsed.version}).`,
  );
  for (const f of relativeFiles.slice(0, 8)) console.log(`  ${f}`);
  if (relativeFiles.length > 8) {
    console.log(`  … and ${relativeFiles.length - 8} more.`);
  }
}
